OSGeo/OSGeoLive

bin/inchroot.sh, bin/install_java.sh
Projects listed as having issues with architecture installation, should follow this approach to add 64 bit support to their installers.
=> Added architecture argument to install_java.sh

bin/install_cartaro.sh
(1) update to cartaro 1.8 
(2) try to fix #1501 in order to ensure geoserver startup,
it seems not necessary to ensure shutdown of geoserver before executing the startup.sh of GeoServer
=> Pull request for Issue #1501

bin/inchroot.sh, bin/install_docs.sh
Here is a patch to install the debian package of the docs.
I have made a change compared to the current setup (second commit): rather than having the osgeo live docs themselve present at /var/www/html I put them in a subdirectory /var/www/html/osgeolive . I think this is better, because we used to have subdirectories for all the different projects mixed with the different languages of the livedvd. This has the disadvantage that we should check whether all links still work. Feel free to comment if you don't like that.
=> Use debian packages of the docs

bin/setup.sh
When running a workshop, the virtualboximages are very hard to use. I don't see any good reason not to install the virtualbox additions by default. When running natively the drivers will not be loaded.
I just tested this at FOSS4G Europe during the OTB workshop and I found no issues when installing these packages on a lot of different combinations of Virtualbox/different host os'es.
=> Install virtualbox guest additions by default

bin/install_grass.sh
Trying my my tutorial for FOSS4G 2015 in Seoul I discovered that the GRASS sample data it is not the [official one](https://grass.osgeo.org/download/sample-data/) but another one provide by [Helena Mitasova](http://www4.ncsu.edu/~hmitaso/grasswork/grassbookdat4ed/). I also discovered that this dataset as at least one dataset broken (landuse).
Regards 
Luca
=> replace GRASS dataset with the one maintained by GRASS community

app-conf/geonetwork/startup.sh
@kalxas - the problem is not consistent, only difference I can see is that permgen space has been increased between 3.0.1 and 3.0.3.
=> Increase permgen space

bin/install_jupyter.sh
Testing a notebook which use ```gdalinfo```:
The program 'gdalinfo' is currently not installed. You can install it by typing:
sudo apt-get install gdal-bin
=> add gdal-bin dependency

bin/tools/debian-vs-osgeolive.pl
This script was initially sent to the mailinglist in the [Comparing package versions between OSGeo-Live, Debian & Ubuntu](https://lists.osgeo.org/pipermail/live-demo/2016-July/011569.html) thread. I think is deserves a more proper home where improvements can be made, and be more accessible to OSGeo-Live developers.
This version contains a minor improvement to only consider the latest version in Debian and Ubuntu if UDD has records for multiple versions in the same release, this currently affects mapserver and mapnik for example, for which only the oldest version was used in the comparison instead of the latest.
=> Add debian-vs-osgeolive.pl script to tools.

bin/install_geonode.sh
GeoServer was broken by the retirement of Cartaro, which was cleaning up after ```install_geonode.sh```. See discussion:
http://osgeo-org.1560.x6.nabble.com/Permissions-problems-with-GeoServer-td5298736.html
=> Grant ordinary users write access to GeoServer resources created by install_geonode.sh

bin/build_chroot.sh
Both the original Lubuntu ISO and the OSGeo Live ISO contained all the UEFI/GRUB2 boot infrastructure. Just a matter of registering it with mkisofs (genisoimage).
=> Create isohybrid ISO images with UEFI support

bin/setdown.sh, bin/setup.sh
Adding user to vboxsf group to permit to access to the shared folders at log on.
Before that you had to add user to the group then log out and log in to use the virtualbox shared folder.
=> Fix - Adding user to vboxsf group to permit to access to the shared folders

bin/install_mapserver.sh, bin/labs/install_i3geo.sh
Requires the mapserver 7.0.4 package for OSGeo-Live 10.5:
https://anonscm.debian.org/cgit/pkg-grass/mapserver.git/log/?h=osgeo/10.5
=> Use php-mapscript package instead of php5{,.6}-mapscript.

desktop-conf/welcome_message.txt
The welcome message refers to "DVD" even when it is often not. I also propose removing "GIS" as I have never heard it used. I think OSGeo Live is a sufficiently distinctive brand.
=> Remove mention of DVD and GIS from welcome message

bin/install_geoserver.sh
Without this symlink, the quickstart would need to be updated every time GeoServer is upgraded.
=> Add unversioned symlink to GeoServer home (used in quickstart)

bin/install_geoserver.sh
GeoServer NetCDF writes hidden index files in the directory containing each NetCDF file, and fails horribly with unhelpful error messages when reading NetCDF files from directories to which it does not have write access. Yes, even just reading. The poorly-documented workaround is to specify another directory with the ```-DNETCDF_DATA_DIR``` Java system property. This pull request applies the workaround, placing index files in ```$HOME/.geoserver```, allowing sample NetCDF data already included in the OSGeo Live disk to be used without first having to copy it to a writeable directory.
Only ```start_admin.sh``` is adjusted. Anyone using ```startup.sh``` must make their own arrangements.
=> Set writable location for GeoServer NetCDF index files

bin/install_geomoose.sh
This is a small fix for a security vulnerability in 2.9.2 that was disclosed to the GeoMoose team today.  I know it is likely too late for OSGeoLive 10.5.  The bug probably isn't a big deal in context of OSGeoLive (which is not meant to serve sites to the internet), but the GeoMoose team would like everyone to move to the latest version as soon as practical.
=> Update GeoMoose to version 2.9.3.

bin/install_52nSOS.sh
Remove version information from war file
See https://trac.osgeo.org/osgeo/ticket/1935
=> 52nSOS: build error: fix osgeo.trac#1935

bin/install_udig.sh
unzip to /usr/lib/udig because the zip doesn't contain neither a root folder udig nor a root folder with version info or something similiar
=> [uDig] fix unzip to UDIG_FOLDER

bin/build_chroot.sh
As per PSC motion 2017-11-06:
http://irclogs.geoapt.com/osgeolive/%23osgeolive.2017-11-06.log
=> Remove hyphen from iso name

CHANGES.txt, bin/install_udig.sh
Release-Notes and further details see : [uDig 2.0.0](https://github.com/locationtech/udig-platform/releases/tag/release%2F2.0.0)
**NOTE** : it requires Java 1.8++ which is already used on OSGeo Live I guess
Signed-off-by: Frank Gasdorf <Frank.Gasdorf@plath.de>
=> Update uDig to version 2.0.0

bin/tools/debian-vs-osgeolive.pl
Note that the script will fail to download the nightly PPA metadata, because there are no packages for bionic yet.
This PR should be merged after the first package for bionic is in the PPA.
=> Switch default Ubuntu distribution to bionic.

bin/install_geomoose.sh, bin/install_icons_and_menus.sh
GeoMoose 3.y has been in the wild for about 9 months and is the latest and greatest.  There will likely be a couple of minor releases worth incorporating before the June freeze, but I would like to get the major version updated early in the process.
Note: GeoMoose 3.y dropped the use of PHP and instead uses standard WFS calls and client side JavaScript, so the MapScript/PHP 7 issue no longer effects us.
=> Update GeoMoose to version 3.1.0

bin/install_mapbender.sh
* the new download package with PHP 7.2 support is mapbender3-starter-3.0.7.0-RC2
* soory. somehow I did not change the name of the package mapbender3-starter-3.0.7.0-RC2
=> refer to mapbender3-starter-3.0.7.0-RC2 which works with PHP7.2

bin/setdown.sh
Should fix issue #1992: https://trac.osgeo.org/osgeolive/ticket/1992
**not tested**
Source: https://askubuntu.com/questions/814/how-to-run-scripts-on-start-up/719157#719157
@kalxas @darkblue-b
=> #1992 fix sf shared folder

bin/install_otb.sh
change one internal OTB python dir to writeable by user, required for python to init the interface by writing a dot-pyc
=> perm fixup on otbApplication dir

bin/install_R.sh, bin/setdown.sh
ipython requires a `tests/` directory to start
=> ipython typo

bin/install_mapbender.sh
* Updated Mapbender to version 3.0.8
* documentation is not part of the package anymore. So no need to delete it
=> updated mapbender to 3.0.8 + no doc rm

bin/install_mapproxy.sh, bin/install_mapserver.sh
This pull request installs the Itasca MapServer demo from a (newly) tagged release on GitHub (see https://github.com/mapserver/mapserver-demo/releases). 
The updated map includes the OSGeoLive hacks which can now be removed. The Itasca map also includes updates to work with the demo GeoExt application (see #257). 
The script allows version numbers to be more easily updated. 
Finally the mapproxy config has been updated to point to the non-symlinked version of the Itasca map. The symlink is still required for the MapServer CGI demo - this may be updated in the future to remove some of the symlinks setup by this script.
=> Update Mapserver Demo link

bin/install_mapserver.sh
Update the built HTML MapServer docs to the new 7.4 release.
Currently there seems no obvious way of finding these docs so the link will also open along with the demo when clicking on MapServer in the menu (this approach is used by a few other projects on OSGeoLive).
=> Update MapServer Docs

app-conf/mapcache/index.html, app-conf/mapcache/mapcache-quickstart.xml, bin/install_icons_and_menus.sh, bin/install_mapcache.sh
This pull request installs MapCache from ubuntugis, along with the relevant files required for the quick start. 
Note the quick start requires OL4 and is loaded via a URL. Alternatives to this would be to install another copy of OL4 for MapCache, or use one installed from another project e.g. GeoExt. 
Overview and quickstart docs to follow and will be linked to from here.
=> Add the MapCache Project

bin/install_mapserver.sh
Two changes to the MapServer installer:
- Use new MapServer Itasca demo which allows for transparent PNG images (required for the MapCache demo)
- Renamed Mapserver to MapServer in the menu title (to make it consistent with MapCache)
=> Update Mapserver to MapServer and update demo to new release

bin/tools/debian-vs-osgeolive.pl
The UDD mirror has moved [[1](https://lists.debian.org/debian-project/2020/11/msg00015.html)], and the nightly repo now includes packages for focal.
=> Update UDD mirror hostname & PPA series.

app-conf/pygeoapi/pygeoapi-config.yml
Fixes https://trac.osgeo.org/osgeolive/ticket/2284 and updates tile server (fixes https://github.com/geopython/pygeoapi/issues/567).
=> update pygeoapi to 0.9.0 configuration

bin/inchroot.sh, bin/install_geostyler.sh
This removes the GeoStyler libraries and just keeps the beginner tutorial, as mentioned in https://github.com/OSGeo/OSGeoLive/pull/285#issuecomment-745987721.
=> Update GeoStyler install script

bin/install_trex.sh
Fixes escaping in t-rex.desktop file (https://trac.osgeo.org/osgeolive/ticket/2280).
=> Update t-rex to 0.13.0 and use TCP connection

bin/install_mapserver.sh
I think this will address ticket 2329. Allows mapfiles upstream of /usr/local and would cover both the MapServer/MapCache demo(s) and GeoMoose. Both examples below validate:
- /usr/local/geomoose/gm3-demo-data/test.map
- /usr/local/www/docs_maps/mapserver/demos/test.map
--Steve
=> Update install_mapserver.sh to be a bit more liberal on where mapfiles can be read from.

bin/install_mapserver.sh
Trying a new pattern to accommodate the /./ directory segments in the GeoMoose setup (see ticket 2329). Also preemptively included a pattern to allow /./ for newer versions of MapServer that do validation in two steps.
These pattern map values match:
- /usr/local/geomoose/gm3-demo-data/./demo/parcels/parcels.map
- /usr/local/geomoose/gm3-demo-data/demo/parcels/parcels.map
- /usr/local/mapserver/demo/itasca/itasca.map
--Steve
=> Update install_mapserver.sh for ticket 2329.

bin/install_mapserver.sh
Version of regex library installed doesn't like \- in the character sets for directories and filenames. The regex compiles fine but doesn't evaluate correctly. Moving it as just - to the front of those character sets seems to fix things using the nightly OSGeo ISO.
=> Update install_mapserver.sh (ticket 2329)

bin/base_c.sh
feel free to download/move the **updated install archive**. for ease of installation it contains the full paths where the files need to be located now. so using this updated 'gdal-3.4.3+dfsg-java.**20220622**.tgz' is mandatory for this PR to work!
=> Fetch/Install prebuilt gdal 3.4.3 libgdal-java components

app-conf/leaflet/leaflet-demo.html
I shifted the coordinates to FOSS4G 2022 Firenze location.
About the marker location, I picked the value from the following official site's uMap attributes.
- https://2022.foss4g.org/
- Bottom Left Map:
- <img src="https://user-images.githubusercontent.com/629923/182019444-d95d3365-8987-4b12-ab72-0b97209d39ca.png" width="200px" alt="2022-foss4g-org-bottom-left-map-url" />
- https://umap.openstreetmap.fr/it/map/foss4g-2022-sites_776000#14/43.7867/11.2554
- https://umap.openstreetmap.fr/ajax-proxy/?url=https%3A%2F%2F2022.foss4g.org%2Ffoss4g2022_venues.geojson&ttl=
```json
{
"type": "FeatureCollection",
"features": [
{
"type": "Feature",
"properties": {
"venue": "Firenze Fiera Congress & Exhibition Center",
"event": "Keynotes, speeches and main events",
"url": …
```
=> Update leaflet-demo with FOSS4G 2022 Firenze location

bin/install_mapserver.sh
Update docs to match installed version. The file http://download.osgeo.org/livedvd/data/mapserver/mapserver-7-6-html-docs.zip does exist.
=> Bump MapServer docs version

app-conf/mapserver/mapserver.conf, bin/install_mapserver.sh
This pull requests includes the following:
- points to the new updated demo (see https://github.com/MapServer/MapServer-demo/pull/7 - a new v1.2 tag was created for this
- adds a new CONFIG file required for MapServer 8.0. Move the current environment variables from Apache to the CONFIG file
- adds a new ITASCA setting to the CONFIG file (so it can be used for the OGC Features API - can add some notes to the quickstart on this)
- adds in the new `php-mapscript-ng` module
Note these changes haven't been tested with a full build of the OSGeoLive ISO, so there may need to be tweaks after a new beta build. 
TODO:
=> Updates for Mapserver 8.0

app-conf/mapserver/mapserver.conf, bin/install_mapserver.sh
A couple of minor updates following testing on the new `osgeolive-nightly-build28-amd64-20c99ee-master.iso` release. 
I've uploaded the latest docs to https://www.dropbox.com/s/oo9sulhheac7ejw/mapserver-8-0-html-docs.zip?dl=0 using the same naming convention / structure as previously. 
@kalxas do you have permissions to upload this file to http://download.osgeo.org/livedvd/data/mapserver/ ?
Once that zip is in place this pull request can be merged to update to the 8.0 MapServer docs. 
- `PROJ_LIB` setting in the `CONFIG` file has been removed as this location is a default anyway
I tested the new demo updates with the OGC Features API available in MapServer 8.0 and it seems to be working fine with the plain templates. Sample URLs:
+ http://locahost/cgi-bin/mapserv/itasca/ogcapi/ 
+ …
=> Updates to MapServer 8.0 setup

bin/install_actinia.sh
- minor updates
- fixes `grass: error: unrecognized arguments: -text` (https://trac.osgeo.org/osgeolive/ticket/2424)
- fixes path to `actinia_logo.png`
TODO: should next (in line 70 of `install_actinia.sh`) become a pip install?
`apt-get --assume-yes install python3-actinia-core python3-actinia-statistic-plugin`
=> install_actinia.sh: actinia install error

bin/install_etf.sh
Modified script to solve a jetty installation issue in OSGeoLive 16.
Jetty is not properly installed in one single execution causing that the .etf is not generated.
It needed to be executed twice in order to make it work.
Actions taken:
- apt-get updated before executing scripts
- Jetty installation run as "user"
=> Update ETF for OSGeoLive 16

bin/install_qfield.sh
As discussed on the mailing list, this adds an installer for QField.
I wasn't able to test it, I just ran it in a simple `ubuntu:22.04` environment to check if it runs through. It might need some fine tuning with dependencies.
<details><summary>This installs an AppImage build that is built as part of the release CI pipelines. Read more about alternatives</summary>
This includes all dependencies required for QField. The [build pipeline lives here](https://github.com/opengisch/QField/blob/master/.github/workflows/linux.yml)
I have looked into some alternatives
1. building with the installed QGIS as dependency, however any recent QField version requires more recent versions of QField and installing an older version would sacrifice a lot of bugfixes that have landed in the last couple of …
=> Add qfield installation

bin/install_qfield.sh
This fixes various things in QField:
1. Install fuse which is required to run AppImage
2. Configure fonts correctly (monospace fonts are cool to code, but not everywhere)
3. Avoid a ~1 minute freeze on startup caused by waiting for bluetooth devices
=> [qfield] Install fuse, otherwise it will not run

bin/build_chroot.sh, bin/setdown.sh
Related with the following Trac tickets:
- [#2429 (Base Lubuntu ISO image needs to be stored in somewhere) – OSGeoLive](https://trac.osgeo.org/osgeolive/ticket/2429)
- [#467 (remove bulky orphaned packages) – OSGeoLive](https://trac.osgeo.org/osgeolive/ticket/467)
Upgrading base Lubuntu ISO image to 22.04.2 caused over 4G error, so I am trying to remove the following packages and caches.
- apt packages
- `libicu-dev`
- `libc6-dev`
- `apt-xapian-index`
- caches
- `/var/lib/apt/lists/*`
=> Upgrade base Lubuntu ISO image to 22.04.2 with removing unnecessary packages and caches

bin/install_cesium.sh
CesiumJS released 1.106 at 2023-06-01,
https://github.com/CesiumGS/cesium/releases/tag/1.106
and I encountered the following error again with the latest nightly build ([osgeolive-nightly-build76-amd64-f2c311c-master.iso](https://download.osgeo.org/livedvd/nightly/osgeolive-nightly-build76-amd64-f2c311c-master.iso)).
[#2398 (Cesium doesn't show a map with InvalidCredentials (401) error) – OSGeoLive](https://trac.osgeo.org/osgeolive/ticket/2398)
---
So, I updated the Cesium version like the previous commit (https://github.com/OSGeo/OSGeoLive/commit/af015489f7abd8e0c98c8c35d4ec485568d8dfc4), and confirmed that the error was not happened.
One good point with this upgrade is "Google Photorealistic 3D Tiles" (since [1.105.1](https://github.com/CesiumGS/cesium/releases/tag/1.105.1)) examples are …
=> Update Cesium to version 1.106

bin/install_actinia.sh
This PR suggests to change the installation of actinia-core from online located wheel to PyPI.
=> Change actinia installation to PyPI

bin/install_actinia.sh
This PR
- updates versions of actinia plugins
- removes separate installation of actinia-api as it is automatically installed with `pip install actinia-core`. This way, no version mismatch can occur.
~~(Draft as not tested yet)~~
=> Update actinia versions

bin/load_gisdata.sh
The Natural Earth download links have changed. See https://github.com/nvkelso/natural-earth-vector/issues/903 and https://github.com/nvkelso/natural-earth-vector/issues/246#issuecomment-1134290221 and this pull request updates the script to use the new URL structure. 
Originally I thought this was the cause of missing data described in https://trac.osgeo.org/osgeolive/ticket/2481 however it appears the download code is not used as `USE_NE_UNMODIFIED=false` means the package from http://download.osgeo.org/livedvd/data/natural_earth2/all_10m_20.tgz is downloaded instead. 
This pull request should however help if `USE_NE_UNMODIFIED` is ever switched back to `true`.
=> Update Natural Earth download links

app-conf/mapserver/mapserver.conf, bin/install_mapserver.sh
This pull request includes the following changes:
- allows Mapfiles to be loaded from any location. As discussed in https://github.com/OSGeo/OSGeoLive-doc/pull/869 - the quickstart asks uses to save files in the `/home/user` directory. The current `MS_MAP_PATTERN` only allowed for Mapfiles in `/usr/local`.
- Grants execute permissions on the `/home/user` directory (execute in this case means the user can read the contents, not execute scripts). Without this MapServer can't read the file and returns `msLoadMap(): Unable to access file. (/home/user/mapserver_quickstart.map)`.
- Switches the docs download to HTTPS
=> MapServer fixes to allow Mapfiles in /home/user

bin/install_etf.sh
Updated the ETF installation file to be compatible with both the new OsGeoLive 17 and JDK 11.
Updated user identification and assignation on folders permits.
Updated Java version and check for it before installing.
Ensure the java Version is the one required in both the start and stop script.
=> Updated ETF install file for OSGeoLive 17 to work with new OS and Java version

bin/install_cesium.sh
I noticed that Cesium doesn't show a map with token error again in the nightly build95 iso.
I am not sure whether today's Cesium 1.123 release affected the issue.
* https://trac.osgeo.org/osgeolive/ticket/2398
* https://x.com/CesiumJS/status/1852475682640539703
Updating Cesium version from 1.121 to 1.123 resolved the issue on my local built iso, so reviewing this is helpful.
=> Update Cesium from 1.121 to 1.123

bin/install_mapbender.sh
deleted not needed installation steps
=> fixed acl error in install_mapbender.sh - two rows deleted not needed

app-conf/mapserver/mapserver.conf
Likely due to the switching to use [PCRE2 instead of POSIX]( https://github.com/MapServer/MapServer/pull/7073) the regex used in `mapserver.conf` for `MS_MAP_BAD_PATTERN` is throwing errors: `MS_MAP_BAD_PATTERN "[/\\]{2}|[/\\]?\.{2,}[/\\]|,"`:
Removing this from the config file means the valid default is used from https://github.com/MapServer/MapServer/blob/d54aae0311066e116974ef888b82959bcefb8c24/src/mapservutil.c#L174
`const char *ms_map_bad_pattern_default = "[/\\\\]{2}|[/\\\\]?\\.+[/\\\\]|,";`
With this update, the MapServer demo is working again for me using osgeolive-nightly-build130-amd64-663f4e3-master.iso
@kalxas - should fix https://trac.osgeo.org/osgeolive/ticket/2501
=> Remove MS_MAP_BAD_PATTERN from mapserver.conf
